kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-017948b4222ebc498
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/data" # optional
  # reuseAccessPoint: "false" # optional
  # ensureUniqueDirectory: "true" # optional
  # subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional